# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "POLITIC" ("ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"NAME" VARCHAR NOT NULL,"DATE_INSERT" TIMESTAMP NOT NULL);
create table "RECORD" ("ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"DATE_INSERT" TIMESTAMP NOT NULL,"FRIENDS" BIGINT NOT NULL,"POLITIC" BIGINT NOT NULL);
create unique index "INDEX_UNIQUE_RECORD" on "RECORD" ("DATE_INSERT","POLITIC");
alter table "RECORD" add constraint "FK_POLITIC" foreign key("POLITIC") references "POLITIC"("ID") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "RECORD" drop constraint "FK_POLITIC";
drop table "POLITIC";
drop table "RECORD";

